apiVersion: v1
kind: Secret
metadata:
  name: retell-webhook-secrets
  labels:
    app: retell-webhook-service
    #  namespace: retell-webhooks
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # echo -n "your-retell-api-key" | base64
  retell-api-key: a2V5XzQ4MDRkZDI5ZWVmY2I4OWI3MzkyZGI1OWI1YTU=

  # echo -n "your-webhook-hash" | base64
  webhook-hash: YzU5OTlmYzgtYWZmMy00MDVkLWFlYmYtYzVjOTA0NTY2YTBi

  # echo -n "https://your-target-endpoint.com/webhook" |  base64 -w 0
  # forward-endpoint: aHR0cHM6Ly9uOG4uYXJkbnQuaW8vd2ViaG9vay10ZXN0L2M1OTk5ZmM4LWFmZjMtNDA1ZC1hZWJmLWM1YzkwNDU2NmEwYg==
  forward-endpoint: aHR0cDovL3JldGVsbC13ZWJob29rLXByb2Nlc3Nvci1zZXJ2aWNlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwvYXBpL3dlYmhvb2svcmV0ZWxs
